export default [
  { name: 'Stk', step: 1 },
  { name: 'Pkg', step: 1 },
  { name: 'g', step: 100 },
  { name: 'kg', step: 1 },
  { name: 'ml', step: 100 },
  { name: 'L', step: 1 },
  { name: 'Kopf', step: 1 },
  { name: 'Glas', step: 1 },
  { name: 'Dose', step: 1 },
  { name: 'Zehen', step: 1 },
  { name: 'Würfel', step: 1 },
  { name: 'Bund', step: 1 },
  { name: 'TL', step: 1 },
  { name: 'EL', step: 1 },
  { name: 'Scheiben', step: 1 },
  { name: 'Knollen', step: 1 },
]
