---
name: CI / CD for homagix/homagix-server
on:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    name: Test, build and push to Dockerhub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@57396166ad8aefe6098280995947635806a0e6ea # tag=v4
        with:
          images: joschi64/homagix-server

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build frontend files
        run: npm run build --if-present

      - name: Test
        run: npm test
        env:
          CI: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # tag=v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 # v3
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Webhook
        uses: joelwmale/webhook-action@c9072d53a3c58619a7807ab49682d6cca61416e2
        with:
          url: ${{ secrets.UPDATE_WEBHOOK }}
