name: update-dependencies

on:
  schedule:
    - cron: "24 11 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      - name: Setup nodejs version
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: ".node-version"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Apply updates
        run: npm run update
  
      - name: Check for modified files
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "modified=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Dependency Updater'
          git config --global user.email 'updater@users.noreply.github.com'
          git commit -am "chore: update dependencies"
          git push
